Solution for Height Checker
austyhooong/LeetcodeRepo pull request #17
Opened 2024-02-22 17:07 UTC by salozzo86

Solution for [Height Checker](https://leetcode.com/problems/height-checker/)

2024-02-26 02:18 UTC, austyhooong commented on Arrays/HeightChecker.java
> +        int[] expected = Arrays.copyOf(heights, heights.length);
if you're using, variable int length, it can be declared in the beginning here

2024-02-26 02:23 UTC, austyhooong reviewed
Great solution!

Little picky but the variable name can be further enhanced by as below:

expected => expectedHeight
min => minHeight
temp => currenthHeight

in the production code in Indeed repo, you can see that the variables are always expressive so its very important to grow the habit early on!

In terms of the time complexity, this is the best we can get with what we have learned so far. In the future once we learn about sorting this can be reduced to nlogn and n (counting sort) (for counting sort, I referred to the solution and this is really cool algorithm we can dive deeper in the future:)

2024-02-27 12:36 UTC, austyhooong requested changes
request for review

2024-02-28 22:36 UTC, salozzo86 commented
Renamed variables more meaningfully! Thanks for flagging these things, it helps with best practices.

2024-02-28 22:37 UTC, salozzo86 commented on Arrays/HeightChecker.java
> +        int[] expected = Arrays.copyOf(heights, heights.length);
Which length? The heights.length? 
I'm wondering if it makes such a difference since I use it only there in the expectedHeight array declaration. I also have another height variable declared later.

2024-03-03 15:44 UTC, austyhooong commented on Arrays/HeightChecker.java
> +        int[] expected = Arrays.copyOf(heights, heights.length);
it was only for nit and there is no difference in terms of performace:) however it thought it would make it more readable and if you were to declare length in the middle you might as well make it consistent across the source code.

2024-03-03 15:44 UTC, austyhooong approved these changes

2024-03-03 15:44 UTC, merged